name: Build, test, release

#on:
  #pull_request:
    #branches:
      #- main

# note "create" event is just so our flows trigger on tag pushes that
# are tagged with [ci skip], see https://github.com/orgs/community/discussions/179637
on: [push, create]
#on:
  #push:
    #branches: [ "main", "master" ]

jobs:
  call-build:
    uses: haridusministeerium/workflows/.github/workflows/py-build-publish-app.yml@master
    secrets: inherit
